[functions]
  directory = "netlify/functions/"
  included_files = [
    "_admin_content/**",
    "admin.html",
    "admin.js",
    "style.css"
  ]

[[redirects]]
  from = "/admin"
  to = "/.netlify/functions/admin-auth"
  status = 200
  force = true # Serve the function's response directly

[[redirects]]
  from = "/admin/*"
  to = "/.netlify/functions/admin-auth"
  status = 200 # Serve the function's response directly
